### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '0xa20856'

### ISSUE THREAD

**Issue by TylerMS887** [martinet101/win32mica#10]
My code is:
```python
import tkinter
from tkinter import ttk

import sv_ttk
root = tkinter.Tk()
root.geometry('400x100+200+200') # set new geometry
from win32mica import MICAMODE, ApplyMica
import darkdetect # You can pass the darkdetect return value directly, since the ColorMode accepts bool values (True -> dark, False -> light)
mode = darkdetect.isDark()

hwnd = root.frame() # On a tkinter window
ApplyMica(hwnd, mode)

button = ttk.Button(root, text="Click me!")
button.pack()


# This is where the magic happens
if darkdetect.isDark():
  sv_ttk.set_theme("dark")
else:
  sv_ttk.set_theme("light")

root.mainloop()
```
Applying Win32Mica messed it up.

Is it a bug in Win32Mica, or a bug in my code?

**EDIT:** Here is the backlog appearing when running the scriptL
```
Traceback (most recent call last):
  File "C:\Users\tyler\fluent-tkinter.py", line 12, in <module>
    ApplyMica(hwnd, mode)
  File "C:\Users\tyler\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\win32mica\__init__.py", line 18, in ApplyMica
    HWND = int(HWND)
ValueError: invalid literal for int() with base 10: '0xa20856'
```

**Comment by martinet101** [comment]
What would happen if you were to convert the hexadecimal value to a base 10 integer?

If this fixes the issue I'll push an update with an automatic conversion done.

**Comment by SlavBoi420** [comment]
Can confirm, I too got the same error while using this with sv_ttk (Also I cannot convert it to int10, it shows invalid literal, as shown in the picture)

**Comment by SlavBoi420** [comment]
I used the above way to get win32mica working with tkinter, let me know if it works for you too!

**Comment by martinet101** [comment]
I see now the issue. I have fixed it and I will push a release with a fix

**Comment by martinet101** [comment]
You can now run the latest version by running 
```
pip install --upgrade win32mica
```

**Comment by SlavBoi420** [comment]
Very cool, now I can convert the HWND string to an int of base 16, thanks for the fix!
