### ISSUE TITLE
Everything works but the I cannot close the thing after restoring a minimised window

### ISSUE THREAD

**Issue by SlavBoi420** [martinet101/win32mica#11]
I made a tkinter application which uses this beautiful mica style, and everything worked. The mica applies fine, there are no errors related to HWND, but there is this one issue. When I restore a minimised window, there are no hitboxes for any buttons on the titlebar. This isssue is related to #7 where OP was not able to focus his window. The same thing happens here, but the only clickable buttons are the ones I made by myself in python, the close, maximise and minimise buttons don't really work

From #7 , I found out that this issue was a tkinter one, is it the case here too?

 
![yes](https://user-images.githubusercontent.com/94615466/202881307-69975dfe-60b3-4d5d-bdf4-87e8919809c1.gif)

From this gif, I was trying to click the minimise button again, but the click is registered on the desktop instead of the app itself

**Comment by martinet101** [comment]
Possibly. I have never experienced this issue with Qt.

Could you please share your code so I can test it?

**Comment by sumeshir26** [comment]
This is a tkinter bug which happens whenever you use the `-transperentcolor` attribute.This can be fixed by minimizing and maximizing the application from your code manuallay after applying the mica.

**Comment by SlavBoi420** [comment]
Thanks for your reply @sumeshir26 but this is the issue I have. The app works fine if I just open it like that (the titlebar buttons work), but as you can see in the gif, after minimising, the buttons fail to respond.

**Comment by martinet101** [comment]
Then it is a tkinter bug, and much can't be done about it. It is the same as #7

**Comment by SlavBoi420** [comment]
Alright, thanks for clearing up this doubt :)
