### ISSUE TITLE
Error when applying mica

### ISSUE THREAD

**Issue by sumeshir26** [martinet101/win32mica#2]
Hi! Reallay awsome project!
I get this error when running on tkinter window:
Code:
` ApplyMica(HWND=windll.user32.GetParent(app.winfo_id()), ColorMode=True)`
Error:
````python
  File "D:\Coding\TimerX\main.py", line 783, in makeWindowsBlur
    ApplyMica(HWND=windll.user32.GetParent(app.winfo_id()), ColorMode=True)
  File "C:\Users\suchi\AppData\Local\Programs\Python\Python310\lib\site-packages\win32mica\__init__.py", line 54, in ApplyMica        
    SetWindowCompositionAttribute(HWND, Wca)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected WINDOWCOMPOSITIONATTRIBDATA instance instead of WindowCompositionAttribute
````

**Comment by martinet101** [comment]
Can't you get the hwnd of the window using the  .frame() function?

Becayer you need to apply this on each window, and not in the app itself

**Comment by martinet101** [comment]
*Because


Aditionally, Are you using any kind of library like PythonBlurBehind?

**Comment by sumeshir26** [comment]
I used to, but now removed it. The app's background is transperent for PythonBlurBehind. Should I make it solid again?

**Comment by sumeshir26** [comment]
When using `.frame`, same error

**Comment by martinet101** [comment]
The issue is because of ctypes interferences. My soolution was to use a moded version of it. You only have to remove the declarations of the rgument datatypes.
    
    SetWindowCompositionAttribute.argtypes = (HWND, WINDOWCOMPOSITIONATTRIBDATA)
    SetWindowCompositionAttribute.restype = ctypes.c_int


I also faced the same issue, and finished by modding the module

**Comment by sumeshir26** [comment]
So I need to mod ctypes? I cant find matching lines in this code

**Comment by martinet101** [comment]
No need to mod ctypes but the pythonBlurBehind module

Although it may not be used, when the moduleis imported it interfiers with win32mica because of those two lines in the PythonBlurBehind Module. Commend them (the module will still work) and everyuthing should go fine

**Comment by martinet101** [comment]
https://github.com/martinet101/ElevenClock/blob/main/elevenclock/external/blurwindow.py

This is an exapmle taken from ElevenClock

**Comment by sumeshir26** [comment]
That fixed it! But is there any way to remove the black box on the title or disable ExpandFrameIntoClientArea until the titlebar text is fixed on Beta Channel?

**Comment by martinet101** [comment]
I don't think so. My approach was to literally set an empty string as titlebar and an empty icon on window icon. With this set it does look good

**Comment by sumeshir26** [comment]
Thank you for your help!
