### ISSUE TITLE
Win32mica: Failed to DwmExtendFrameIntoClientArea

### ISSUE THREAD

**Issue by youssefhoummad** [martinet101/win32mica#5]
error while import win32mica

Win32mica: Failed to DwmExtendFrameIntoClientArea

os: windows 11 22000.588
python: 3.10

**Comment by youssefhoummad** [comment]
> Yes, this is a thing i'm also facing, i'm trying to figure out what is happenig. Btw, the mica effect still works despite the line error, right?

No app craching

**Comment by youssefhoummad** [comment]
it work after changing code
    ApplyMica(
        HWND=ctypes.windll.user32.GetParent(root.winfo_id()),
        ColorMode=MICAMODE.LIGHT,
    )

but error still there

**Comment by martinet101** [comment]
The issue shpuld have been now fixed, make sure to update to version 1.5
