### ISSUE TITLE
Compiling with cx_Freeze

### ISSUE THREAD

**Issue by not-nef** [martinet101/win32mica#6]
Hello! I am using win32mica in a program, and when running the program from the .py file, everything works flawlessly. But when i compile the program to an execuetable using cx_Freeze, win32mica throws the following error:

`Win32Mica Error: win32 version 9200 is not supported`

What does that mean and how do i fix it?

**Comment by martinet101** [comment]
Mhmm, that's weird... It looks that cx_freeze is not providing a correct windows build number...

Could you try build using PyInstaller?

**Comment by not-nef** [comment]
I can, but does pyinstaller build msi's?

**Comment by martinet101** [comment]
PyInstaller will build a standalone .exe file, and then you can create an installer using tools like Inno Setup (will create a .exe installer) or AppDeploy Repackager (will create a .msi installer)

**Comment by not-nef** [comment]
Epic, ok. How do i use pyinstaller? (Sorry for bothering you)

**Comment by martinet101** [comment]
It is really easy (actually easier than cx_freeze).

1. install pyinstaller:
```
pip install pyinstaller
```

2. Build the .exe file:
```
pyinstaller ./yourfile.py --onefile --windowed
```

3. You will have a .exe file in a folder located in your current working directory called dist. It should work then. 

For more info check out the docs: https://pyinstaller.org/en/stable/usage.html

**Comment by martinet101** [comment]
Hi, did that help with the issue?

**Comment by not-nef** [comment]
I am still having troubles with another of the apps components, but once its fixed, i will report to you if it works!

**Comment by not-nef** [comment]
Yes @martinet101 it works, thank you
