### ISSUE TITLE
Title bar label background colour

### ISSUE THREAD

**Issue by Cowski0** [martinet101/win32mica#8]
is there a way to stop the background color on the label of the window, i kinda resorted to just leaving the title bar empty because it was annoying.

**Comment by sumeshir26** [comment]
Hey, this is a windows bug and is alreaday fixed, it will release soon

**Comment by martinet101** [comment]
True, this will be fixed on Windows 11 22h2, coming this september

**Comment by martinet101** [comment]
@Cowski0, if you want to set an empty titlebar, you will need to use some kind of empty character instead of a empty `""` string, such as "`\u200b`", because otherwise the title will default to `python`

**Comment by sumeshir26** [comment]
On Tkinter, even `""` works

**Comment by martinet101** [comment]
Ah, in my case it was with Qt

**Comment by Cowski0** [comment]
Alright, thanks
